[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_bridge = "7xe9EhqT7bQe5T142Zbxt8TxbkArhSFyRjtd8xDD2uAv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/cr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
