[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_bridge = "6gUrEYhacs6ZeHZFfDEBih1PRY7417vTYZjbfD62mkjV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
